--ALTER TABLE SUB_FASES ADD COLUMN SUB_SIGLA  CHAR(4) NULL;
--update SUB_FASES set SUB_SIGLA = '';
--ALTER TABLE SUB_FASES ALTER COLUMN SUB_SIGLA  NOT NULL;
ALTER TABLE ANAGRAMA_ESTIMULOS ALTER COLUMN ANA_EST_TIPO  CHAR(1);